name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.0.1
  firebase_messaging: ^10.0.3
  flutter_facebook_auth: ^3.5.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^6.0.0
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  get_it: ^7.1.3
  google_maps_flutter: ^2.0.1
  google_sign_in: ^5.0.4
  image_picker: ^0.8.1+3
  path_provider: ^2.0.1
  pin_code_fields: ^7.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.0.2

# dependency overrides:
#  intl: "0.16.1"
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
