/// Flutter icons CustomIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String _kFontPkg = null;

  static const IconData f_orders = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_cart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_explore = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
